server:
  port: 80
  servlet:
    context-path: /v4/

spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kty_commission
    username: root
    password: 1234

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
